# This tool was written by @keyiflerolsun | for @KekikAkademi

name: CapRover Deployer

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name   : Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "22"

      - name: Install CapRover CLI
        run : npm i -g caprover

      - name: Check for Changes
        id  : check_changes
        run : |
          # Detect changes in relevant file types to trigger deployment
          if git diff --name-only HEAD^ | grep -qE '\.(py|toml|txt|j2|html|css|js|json|yaml|yml)$'; then
            echo "deploy=true" >> $GITHUB_OUTPUT
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Deploy TarBall
        if  : steps.check_changes.outputs.deploy == 'true'
        uses: a7ul/tar-action@v1.2.0
        with:
          command: c
          cwd    : "./"
          files  : ./
          outPath: deploy.tar

      - name: Deploy to CapRover
        if  : steps.check_changes.outputs.deploy == 'true'
        run : |
          caprover deploy --caproverUrl "${{ secrets.SERVER }}" \
          --appToken "${{ secrets.PROVIDER_TOKEN }}" \
          --appName " ${{ secrets.PROVIDER_APP }}" \
          --tarFile ./deploy.tar
